"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$localip\
$shlvl\
[in ]()\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$python\
$rust\
$vagrant\
$conda\
$meson\
$spack\
$memory_usage\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$battery\
$line_break\
$time\
$os\
$container\
$shell\
$character\
"""

right_format = """
$jobs\
$status\
${env_var.OLEDCOMM_ENV}\
"""

add_newline = false

[env_var.OLEDCOMM_ENV]
format = "[\\($env_value\\)]($style)"
default = "normal"
style = "bold red"

## FIRST LINE/ROW: Info & Status
# First param ‚îÄ‚îå
[username]
format = " [‚ï≠‚îÄ $user]($style)@"
style_user = "bold red"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "‚á°${count}"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "‚á£${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = true

# Prompt: optional param 1
[time]
format = " üïô $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 ‚îî‚îÄ
[character]
success_symbol = " [‚ï∞‚îÄŒª](bold red)"
error_symbol = " [‚ï∞‚îÄ√ó](bold red)"

# SYMBOLS
[status]
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
pipestatus_format = '\[$pipestatus\] => [$common_meaning$signal_name$maybe_int]($style) '
map_symbol = false
disabled = false
pipestatus = false

[jobs]
threshold = 1
number_threshold = 1
symbol_threshold = 1
symbol = 'J'
format = '[\[$number\]]($style) '
style = 'blue'
disabled = false

[aws]
symbol = "ÓåΩ  "

[conda]
symbol = "ÔÑå "

[dart]
symbol = "Óûò "

#[directory]
#read_only = " Ô†Ω"

[docker_context]
symbol = "Ôåà "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = "Óâµ "

[elm]
symbol = "Óò¨ "

[git_branch]
symbol = "Ôêò "

[golang]
symbol = "Óòß "

[hg_branch]
symbol = "Ôêò "

[java]
symbol = "Óâñ "

[julia]
symbol = "Óò§ "

[haskell]
symbol = "Œª "

[memory_usage]
symbol = "Ô°ö "

[nim]
symbol = "Ôö§ "

[nix_shell]
symbol = "Ôãú "

[package]
symbol = "Ô£ñ "

[perl]
symbol = "Óù© "

[php]
symbol = "Óòà "

[python]
symbol = "ÓòÜ "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = "Óàæ "

[rust]
symbol = "Óû® "

[scala]
symbol = "Óú∑ "

[shlvl]
symbol = "ÔÑ† "
format = '[$symbol$shlvl]($style) '
disabled = true

[swift]
symbol = "ÔØ£ "

[nodejs]
format = "via [Ô¢ò Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
